;              
CREATE USER IF NOT EXISTS "SA" SALT '6580703c953b52f6' HASH '1e9d30321447f8530e042e4df62cd39fa1ac58f36da2b4aa639bc87fcdd1a7e9' ADMIN;          
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;    
CREATE CACHED TABLE "PUBLIC"."ADDRESS"(
    "ID" BIGINT NOT NULL,
    "ADDED_OR_UPDATED" BOOLEAN NOT NULL,
    "EXTERNAL_ID" VARCHAR(255),
    "CITY" VARCHAR(255),
    "NUMBER" BIGINT,
    "POSTAL_CODE" VARCHAR(255),
    "STREET" VARCHAR(255)
);          
ALTER TABLE "PUBLIC"."ADDRESS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADDRESS;  
CREATE CACHED TABLE "PUBLIC"."EVENT"(
    "ACTION" VARCHAR(31) NOT NULL,
    "ID" BIGINT NOT NULL,
    "ADDED_OR_UPDATED" BOOLEAN NOT NULL,
    "EXTERNAL_ID" VARCHAR(255),
    "ACCEPTED" BOOLEAN NOT NULL,
    "COMMENT" VARCHAR(255),
    "CREATION_DATE" TIMESTAMP,
    "OBJECT_ID" BIGINT,
    "PROCESSED" BOOLEAN NOT NULL,
    "READ" BOOLEAN NOT NULL,
    "STATUS" VARCHAR(255),
    "TYPE" VARCHAR(255),
    "QUANTITY" BIGINT,
    "DESTINATION_WAREHOUSE_ID" BIGINT
);             
ALTER TABLE "PUBLIC"."EVENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENT;    
CREATE CACHED TABLE "PUBLIC"."ITEM"(
    "ID" BIGINT NOT NULL,
    "ADDED_OR_UPDATED" BOOLEAN NOT NULL,
    "EXTERNAL_ID" VARCHAR(255),
    "QUANTITY" BIGINT,
    "ITEM_TYPE_ID" BIGINT,
    "WAREHOUSE_ID" BIGINT
);         
ALTER TABLE "PUBLIC"."ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM;     
CREATE CACHED TABLE "PUBLIC"."ITEM_TYPE"(
    "ID" BIGINT NOT NULL,
    "ADDED_OR_UPDATED" BOOLEAN NOT NULL,
    "EXTERNAL_ID" VARCHAR(255),
    "CODE" VARCHAR(255),
    "NAME" VARCHAR(255)
);               
ALTER TABLE "PUBLIC"."ITEM_TYPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_28" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM_TYPE;
CREATE CACHED TABLE "PUBLIC"."WAREHOUSE"(
    "ID" BIGINT NOT NULL,
    "ADDED_OR_UPDATED" BOOLEAN NOT NULL,
    "EXTERNAL_ID" VARCHAR(255),
    "CODE" VARCHAR(255),
    "NAME" VARCHAR(255),
    "ADDRESS_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."WAREHOUSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2F" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WAREHOUSE;
ALTER TABLE "PUBLIC"."EVENT" ADD CONSTRAINT "PUBLIC"."FKKTE6C556ARSOEP2MAWET1SXN4" FOREIGN KEY("DESTINATION_WAREHOUSE_ID") REFERENCES "PUBLIC"."WAREHOUSE"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."ITEM" ADD CONSTRAINT "PUBLIC"."FK5XNH745ITP8VE10YFK0S2V01Q" FOREIGN KEY("WAREHOUSE_ID") REFERENCES "PUBLIC"."WAREHOUSE"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."WAREHOUSE" ADD CONSTRAINT "PUBLIC"."FKP7XYMGRE8VT94IHF75E9MOVYT" FOREIGN KEY("ADDRESS_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."ITEM" ADD CONSTRAINT "PUBLIC"."FKH7KYK389QJ2M5CHAA0NJSQ601" FOREIGN KEY("ITEM_TYPE_ID") REFERENCES "PUBLIC"."ITEM_TYPE"("ID") NOCHECK;   
